name = "DACE"
uuid = "d25d0e74-ad23-4390-b8f5-39e36c0e5c3d"
authors = ["Ivan Anashkin <anashkin.ivan@gmail.com>"]
version = "0.1.0"

[deps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
Clapeyron = "0.6.10"
ModelingToolkit = "9.71.0"
